In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("ping_reply.csv")

In [4]:
df.sort(Se)

,SequenceNumber,RequestTime,ReplyTime,RequestSourceIP,RequestDestIP,ReplySourceIP,ReplyDestIP,ReplyTTLexpiredIP,TTL,Download/Upload/Idle
0,13057,14:59:28.303741,14:59:28.318143,10.194.47.140,34.131.115.191,10.255.107.3,10.194.47.140,10.255.107.3,NaN,download
1,13238,14:59:34.293071,14:59:34.297506,10.194.47.140,34.131.115.191,10.254.239.1,10.194.47.140,10.254.239.1,NaN,upload
2,13455,14:59:41.506233,14:59:41.508501,10.194.47.140,34.131.115.191,10.194.32.13,10.194.47.140,10.194.32.13,NaN,idle
3,12998,14:59:26.307636,14:59:26.320519,10.194.47.140,34.131.115.191,10.254.239.1,10.194.47.140,10.254.239.1,NaN,download
4,13124,14:59:30.488184,14:59:30.518286,10.194.47.140,34.131.115.191,10.194.32.13,10.194.47.140,10.194.32.13,NaN,upload
...,...,...,...,...,...,...,...,...,...,...
914,13520,14:59:43.724237,14:59:43.727938,10.194.47.140,34.131.115.191,10.255.107.3,10.194.47.140,10.255.107.3,NaN,idle
915,13590,14:59:46.009368,14:59:46.011379,10.194.47.140,34.131.115.191,10.194.32.13,10.194.47.140,10.194.32.13,NaN,idle
916,12927,14:59:23.912592,14:59:23.929191,10.194.47.140,34.131.115.191,10.194.32.13,10.194.47.140,10.194.32.13,NaN,download
917,13517,14:59:43.602271,14:59:43.604185,10.194.47.140,34.131.115.191,10.254.239.1,10.194.47.140,10.254.239.1,NaN,idle
918,13557,14:59:44.901298,14:59:44.905324,10.194.47.140,34.131.115.191,10.194.32.13,10.194.47.140,10.194.32.13,NaN,idle